# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

gripper:
  type: position_controllers/JointTrajectoryController
  joints:
     - base_to_finger_1


gazebo_ros_control:
  pid_gains:
    base_to_finger_1: {p: 1000.0, i: 0.01, d: 1.0}
    base_to_finger_2: {p: 1000.0, i: 0.01, d: 1.0}


